import { useState } from "react";
import type { HubAssignment, HubClass, HubConcept, HubDraft, HubProgressClass, HubTextbook } from "@/shared/content-types";
import { HubIcon, type IconName } from "./HubIcon";

export type MoreSection = "curriculum" | "drafts" | "library" | "settings";
type StateProps = { loading: boolean; error: boolean };

export function MorePage({ onOpen }: { onOpen: (section: MoreSection) => void }) {
  const items: Array<[MoreSection,string,string,IconName]> = [["curriculum","Curriculum","View textbooks and materials","curriculum"],["drafts","Drafts","Finish setting up Classroom work","drafts"],["library","Library","Solution Library concepts and resources","library"],["settings","Settings","TeacherLyft and Hub settings","settings"]];
  return <Page title="More" subtitle="More TeacherLyft tools"><div className="more-grid">{items.map(([id,title,detail,icon]) => <button className="more-tile" key={id} onClick={() => onOpen(id)}><span className="more-icon"><HubIcon name={icon}/></span><span><strong>{title}</strong><small>{detail}</small></span><HubIcon name="arrow"/></button>)}</div></Page>;
}

function DataState({ loading,error,empty,title,description,children }: StateProps & { empty:boolean; title:string; description:string; children:React.ReactNode }) {
  if (loading) return <div className="screen-state" aria-busy="true">Loading current TeacherLyft data…</div>;
  if (error) return <div className="screen-state error-panel">This section is unavailable. Check the connection and try Refresh.</div>;
  if (empty) return <div className="screen-state empty-state"><strong>{title}</strong><p>{description}</p></div>;
  return <>{children}</>;
}

export function ClassesPage({ items,loading,error,onOpenClass,onOpenStudent }: StateProps & { items:HubClass[]; onOpenClass?:(id:string)=>void; onOpenStudent?:(classId:string,id:string)=>void }) {
  const [open,setOpen] = useState<Set<string>>(new Set());
  const toggle=(id:string)=>setOpen(value=>{const next=new Set(value);if(next.has(id))next.delete(id);else next.add(id);return next;});
  return <Page title="Classes" subtitle="The classes you teach in Google Classroom, with their rosters, read live."><DataState loading={loading} error={error} empty={!items.length} title="No classes yet" description="Classes you teach in Google Classroom appear here automatically. There is nothing to import."><Heading title="Your classes" detail={`${items.length} active ${items.length===1?"class":"classes"}`}/><div className="class-grid">{items.map(item=><article className="teacher-class-card" key={item.id}><button className="class-card-header class-detail-button" onClick={()=>onOpenClass?.(item.id)}><span className="class-symbol">C</span><span><strong>{item.name}</strong><small>{[item.section,item.period].filter(Boolean).join(" · ")||"Class"}</small></span><span>›</span></button><button className="roster-toggle" onClick={()=>toggle(item.id)} aria-expanded={open.has(item.id)}><span>Students</span><span className="roster-count">{item.studentCount} on the roster</span><span>{open.has(item.id)?"−":"+"}</span></button>{open.has(item.id)&&<div className="roster-list">{item.students.length?item.students.map(student=><button className="student-tile" key={student.id} onClick={()=>onOpenStudent?.(item.id,student.id)}><span className="student-avatar">{initials(student.name)}</span><strong>{student.name}</strong><span>›</span></button>):<p>Nobody is on this Google Classroom roster yet.</p>}</div>}</article>)}</div></DataState></Page>;
}

export function AssignmentsPage({ items,loading,error,onOpen }: StateProps & { items:HubAssignment[]; initialToGrade?:boolean; onOpen?:(id:string)=>void }) {
  const [query,setQuery]=useState(""); const shown=items.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())); const groups=groupBy(shown,item=>item.className);
  return <Page title="Assignments" subtitle="Everything you have assigned in Google Classroom, grouped by class."><DataState loading={loading} error={error} empty={!items.length} title="No assignments yet" description="Assignments you create in Google Classroom appear here automatically. There is nothing to import or sync."><div className="assignment-tools"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by assignment title…"/><label>Sort <select><option>Newest</option><option>Oldest</option><option>Due date</option><option>Most submissions</option></select></label></div><div className="class-sections">{groups.map(([name,assignments])=><section className="class-section" key={name}><div className="class-section-toggle"><span><strong>{name}</strong><small>{assignments.length} {assignments.length===1?"assignment":"assignments"}</small></span></div><div className="class-section-body"><div className="compact-metrics"><Metric label="Total" value={assignments.length}/><Metric label="Submissions" value={sum(assignments,"submissionCount")}/><Metric label="Avg AI grade" value={average(assignments)}/><Metric label="Awaiting grade" value={sum(assignments,"toGradeCount")}/></div><div className="assignment-list">{assignments.map(item=><article className="assignment-card" key={item.id}><div className="assignment-main"><h3>{item.title}</h3><p className="uppercase-label">{item.className}</p><p>{item.dueDate?`Due ${formatDate(item.dueDate)}`:"No due date"}</p><p>{item.submissionCount} submissions · {item.gradedCount} graded · {item.toGradeCount} awaiting grade</p></div><div className="assignment-actions"><span className="badge">{item.type}</span><span className="status-chip">{item.status}</span><button onClick={()=>onOpen?.(item.id)}>View details</button></div></article>)}</div></div></section>)}</div></DataState></Page>;
}

export function ProgressPage({ classes,loading,error,onOpenClass }: StateProps & { classes:HubProgressClass[]; onOpenClass?:(id:string)=>void }) {
  const total=(key:keyof HubProgressClass)=>classes.reduce((n,item)=>n+(typeof item[key]==="number"?item[key] as number:0),0);
  return <Page title="Student Progress" subtitle={`Performance, completion and follow-up across ${classes.length||"your"} active classes.`}><DataState loading={loading} error={error} empty={!classes.length} title="No classes yet" description="Create a class to start tracking student progress."><section aria-label="Across all classes" className="progress-overview"><Metric label="Students" value={total("student_count")}/><Metric label="Needing Attention" value={total("needs_attention_count")+total("at_risk_count")}/><Metric label="Missing Work" value={total("missing_count")}/><Metric label="Recent Performance" value={weightedAverage(classes)}/></section><Heading title="Classes"/><div className="progress-grid">{classes.map(item=><article className="progress-card" key={item.id}><header><h2>{item.class_name}</h2></header><div className="progress-figures"><Metric label="Students" value={item.student_count}/><Metric label="Class average" value={percent(item.avg_grade)}/><Metric label="Graded" value={item.graded_count}/></div><div className="completion-row"><span>Turned in <small>past-due work</small></span><strong>{percent(item.completion_rate)}</strong></div><div className="progress-meter"><span style={{width:`${item.completion_rate??0}%`}}/></div><footer><span>{item.assignments_given} assignments</span><span>{item.missing_count} missing</span><span>{item.awaiting_grade_count} awaiting grading</span></footer><button onClick={()=>onOpenClass?.(item.id)}>View class progress</button></article>)}</div></DataState></Page>;
}

export function CurriculumPage({ items,loading,error,unavailable,onOpen }: StateProps & { items:HubTextbook[]; unavailable?:boolean; onOpen?:(id:string)=>void }) { return <Page title="My Curriculum" subtitle="Upload and organize the textbooks you teach from.">{unavailable?<div className="screen-state">Curriculum is not set up yet</div>:<DataState loading={loading} error={error} empty={!items.length} title="No textbooks yet" description="Add the textbooks you teach from. Once uploaded, TeacherLyft will organize it into units and lessons."><div className="page-action"><button disabled>Add Textbook on web</button></div><div className="curriculum-grid">{items.map(item=><article className="curriculum-card" key={item.id}><h2>{item.title||"Untitled textbook"}</h2><p>{[item.subject,item.courseLevel,item.publisher].filter(Boolean).join(" · ")}</p><span className="status-chip">{item.status}</span><dl><dt>Pages</dt><dd>{item.pageCount??item.totalPages??"—"}</dd><dt>Processed</dt><dd>{item.processedPages??"—"}</dd><dt>Structure</dt><dd>{item.structureStatus}</dd></dl><div className="card-actions"><button onClick={()=>onOpen?.(item.id)}>View details</button><button disabled>Organise on web</button><button disabled>Delete on web</button></div></article>)}</div></DataState>}</Page>; }

export function DraftsPage({ items,loading,error,onOpen }: StateProps & { items:HubDraft[]; onOpen?:(id:string)=>void }) { return <Page title="Drafts" subtitle="Google Classroom assignments that have no answer key yet, so TeacherLyft cannot grade them."><DataState loading={loading} error={error} empty={!items.length} title="Nothing waiting on you" description="Every assignment already has an answer key. New ones appear here automatically."><section className="draft-panel"><Heading title={`${items.length} to set up`}/>{items.map(item=><article className="draft-row" key={item.id}><div><h2>{item.title}</h2><p>{item.className} · {item.dueDate?`due ${formatDate(item.dueDate)}`:"no due date"}{item.maxPoints===null?"":` · ${item.maxPoints} points`}</p></div><div className="draft-actions"><button onClick={()=>onOpen?.(item.id)}>View details</button><button disabled>Set up on web →</button></div></article>)}</section></DataState></Page>; }

export function LibraryPage({ items,loading,error,onOpen }: StateProps & { items:HubConcept[]; onOpen?:(id:string)=>void }) { const subjects=groupBy(items,item=>item.subject||"General"); return <Page eyebrow="Teacher Resource Library" title="Solution Library" subtitle="Upload instructional materials and create teaching method templates for Method Match analysis."><div className="page-action"><button disabled>New Concept on web</button></div><DataState loading={loading} error={error} empty={!items.length} title="No concepts yet" description="Create your first concept to get started with Method Match"><div className="subject-groups">{subjects.map(([subject,concepts])=><section className="subject-group" key={subject}><h2>{subject}</h2>{concepts.map(concept=><article className="concept-card" key={concept.id}><div className="concept-heading"><div><h3>{concept.concept_name}</h3><p>{concept.description}</p></div>{Boolean(concept.solution_summaries)&&<span className="ready-chip">Summary Ready</span>}</div><div className="concept-resources"><strong>Resources</strong><button disabled>Upload on web</button></div><button onClick={()=>onOpen?.(concept.id)}>View details</button></article>)}</section>)}</div></DataState></Page>; }

export function SimpleCardsPage({ title,items,loading,error,unavailable }:{title:string;subtitle:string;items:Array<HubDraft|HubTextbook|HubConcept>;loading:boolean;error:boolean;unavailable?:boolean}) { if(title==="Curriculum")return <CurriculumPage items={items as HubTextbook[]} loading={loading} error={error} unavailable={unavailable}/>;if(title==="Drafts")return <DraftsPage items={items as HubDraft[]} loading={loading} error={error}/>;return <LibraryPage items={items as HubConcept[]} loading={loading} error={error}/>; }
export function SettingsPage({ connection,onDisconnect }:{connection:string;onDisconnect:()=>void}) { return <Page title="Settings" subtitle="Manage your connections and personalize your teacher workspace."><div className="settings-groups">{[["School","Connect your account to your school so your principal can see your classes."],["Google Workspace","Connect your school Google account to TeacherLyft."],["Devices","Connect and manage physical TeacherLyft Assistants."],["Appearance","Choose how TeacherLyft looks on this device."]].map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<section className="hub-settings"><h2>Hub device settings</h2><div className="settings-card"><span>Status: {connection}</span><button className="danger-button" onClick={onDisconnect}>Disconnect this device</button></div></section></div></Page>; }

function Page({eyebrow,title,subtitle,children}:{eyebrow?:string;title:string;subtitle:string;children:React.ReactNode}) { return <section className="data-page"><header className="page-header">{eyebrow&&<p className="section-kicker">{eyebrow}</p>}<h1>{title}</h1><p>{subtitle}</p></header>{children}</section>; }
function Heading({title,detail}:{title:string;detail?:string}){return <div className="section-heading"><h2>{title}</h2>{detail&&<span>{detail}</span>}</div>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function groupBy<T>(items:T[],key:(item:T)=>string){const map=new Map<string,T[]>();for(const item of items){const k=key(item);map.set(k,[...(map.get(k)||[]),item])}return [...map.entries()]}
function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function formatDate(value:string){return new Date(value).toLocaleDateString()}
function percent(value:number|null){return value===null?"—":`${Math.round(value)}%`}
function sum(items:HubAssignment[],key:"submissionCount"|"toGradeCount"){return items.reduce((n,item)=>n+item[key],0)}
function average(items:HubAssignment[]){const values=items.map(item=>item.averagePercentage).filter((value):value is number=>value!==null);return values.length?`${Math.round(values.reduce((a,b)=>a+b,0)/values.length)}%`:"—"}
function weightedAverage(items:HubProgressClass[]){const values=items.filter(item=>item.avg_grade!==null&&item.graded_count);return values.length?`${Math.round(values.reduce((n,item)=>n+(item.avg_grade||0)*item.graded_count,0)/values.reduce((n,item)=>n+item.graded_count,0))}%`:"—"}
