import type { DetailKind } from "@/shared/content-types";

type Props={kind:DetailKind;data:Record<string,unknown>|null;loading:boolean;error:boolean;onBack:()=>void;onRetry?:()=>void;onOpenStudent?:(classId:string,id:string)=>void};
export function DetailPage({kind,data,loading,error,onBack,onRetry,onOpenStudent}:Props){return <section className="data-page detail-page"><button className="back-to-more" onClick={onBack}>‹ Back</button>{loading?<div className="screen-state" aria-busy="true">Loading current TeacherLyft data…</div>:error||!data?<div className="screen-state error-panel"><span>This detail is unavailable.</span><button onClick={onRetry}>Retry</button></div>:kind==="class"?<ClassProgress data={data} onOpenStudent={onOpenStudent}/>:kind==="student"?<StudentProgress data={data}/>:kind==="assignment"?<AssignmentDetail data={data}/>:<GenericDetail kind={kind} data={data}/>}</section>}

function AssignmentDetail({data}:{data:Record<string,unknown>}){
 const assignment=obj(data.assignment),answerKey=obj(data.answerKey),counts=obj(data.counts),submissions=list(data.submissions),configured=Boolean(answerKey?.configured),average=maybeNum(data.averagePercentage),points=maybeNum(assignment?.maxPoints),awaiting=num(counts?.awaitingGrade),flagged=num(counts?.flaggedForReview);
 const context=[str(assignment?.className),str(assignment?.section)].filter(Boolean).join(" · ");
 return <>
  <header className="page-header assignment-detail-header"><p className="section-kicker">Assignment</p><div className="assignment-title-line"><h1>{str(assignment?.title)??"Assignment"}</h1>{str(assignment?.status)&&<span className="status-chip">{str(assignment?.status)}</span>}</div>{context&&<p>{context}</p>}<div className="assignment-meta"><span>{str(assignment?.dueDate)?`Due ${date(str(assignment?.dueDate) as string)}`:"No due date"}</span><span>{points===null?"No points set":`${points} points`}</span></div></header>
  {Boolean(data.recordsArePartial)&&<p className="progress-notice">This assignment has more stored results than the Hub reads at once. The most recent are shown.</p>}
  <section aria-label="Assignment summary" className="progress-overview assignment-overview"><Metric label="Submissions" value={num(counts?.handedIn)} support={`${num(counts?.expected)} students expected`}/><Metric label="Graded" value={num(counts?.graded)} support={awaiting?`${awaiting} waiting`:"All handed-in work graded"}/><Metric label="Awaiting Review" value={awaiting} support={flagged?`${flagged} question${flagged===1?"":"s"} flagged`:"No questions flagged"}/><Metric label="Average Grade" value={pct(average)} support={average===null?"No grades yet":"Across graded work"}/></section>
  <Panel title="Grading setup" detail="What this assignment is marked against."><div className="setup-list"><div><span>Answer key</span><strong className={configured?"setup-ready":"setup-needed"}>{configured?"Configured":"Not set"}</strong></div>{configured&&<div><span>Questions</span><strong>{maybeNum(answerKey?.totalQuestions)??"—"}</strong></div>}<div><span>Method taught</span><strong>{str(answerKey?.conceptName)??"Not linked"}</strong></div></div></Panel>
  <Panel title="Student work" detail={submissions.length?`${submissions.length} student${submissions.length===1?"":"s"} in this assignment`:undefined}>{submissions.length?<div className="stacked-list submission-list">{submissions.map((submission,index)=><SubmissionRow key={str(submission.studentId)??index} submission={submission} maxPoints={points}/>)}</div>:<Empty>No students are enrolled in this assignment yet.</Empty>}</Panel>
 </>
}

function SubmissionRow({submission,maxPoints}:{submission:Record<string,unknown>;maxPoints:number|null}){
 const analysis=obj(submission.analysis),questions=obj(analysis?.questions),official=maybeNum(submission.officialGrade),analysisScore=maybeNum(analysis?.score),grade=official??analysisScore,percentage=maybeNum(submission.officialPercentage)??maybeNum(analysis?.percentage),review=num(questions?.flaggedForReview),handedIn=Boolean(submission.handedIn),late=Boolean(submission.late),graded=percentage!==null||str(analysis?.status)==="graded";
 const gradeText=grade!==null?`${grade}${maxPoints!==null?`/${maxPoints}`:""}${percentage!==null?` · ${pct(percentage)}`:""}`:"—";
 return <article className="submission-row"><div className="submission-student"><strong>{str(submission.studentName)??"Student"}</strong><small>{late?"Handed in late":handedIn?"Handed in":"Not handed in"}</small></div><div className="submission-badges"><span className="row-status">{graded?"Graded":handedIn?"Awaiting review":"Missing"}</span>{review>0&&<span className="review-chip">{review} flagged</span>}</div><div className="submission-grade"><strong>{gradeText}</strong><small>Grade</small></div></article>
}

function ClassProgress({data,onOpenStudent}:{data:Record<string,unknown>;onOpenStudent?: (classId:string,id:string)=>void}){
 const course=obj(data.class),metrics=obj(data.metrics),students=list(data.students),assignments=list(data.assignments),groups=list(obj(data.learningGroups)?.groups),classId=str(course?.id)??"";
 const total=students.length,missingStudents=students.filter(s=>num(s.missing_assignments)>0).length,average=maybeNum(metrics?.averagePercentage),missing=num(metrics?.missingCount),awaiting=num(metrics?.awaitingGradeCount),graded=num(metrics?.gradedCount);
 return <><header className="page-header"><h1>{str(course?.name)??"Class progress"}</h1><p>{[str(course?.section),str(course?.room),"Class progress"].filter(Boolean).join(" · ")}</p></header>
 {Boolean(data.countsArePartial)&&<p className="progress-notice">Hand-in state was read for this class’s most recent assignments. Older work shows what TeacherLyft has graded so far.</p>}
 <section aria-label="Class summary" className="progress-overview"><Metric label="Class Average" value={pct(average)} support={graded?`from ${graded} graded assignments`:"No graded work yet"}/><Metric label="Students" value={total} support={total?`${students.filter(s=>num(s.graded_assignments)===0).length} with no graded work yet`:"Nobody on the roster"}/><Metric label="Missing Work" value={missing} support={missing?`across ${missingStudents} students`:"Nothing past due"}/><Metric label="Awaiting Grading" value={awaiting} support={num(metrics?.flaggedForReviewCount)?`${num(metrics?.flaggedForReviewCount)} questions flagged`:"no questions flagged"}/></section>
 <Panel title="Performance Status" detail="Grade bands combined with missing work."><div className="status-grid"><Figure label="On Track" value={num(metrics?.onTrackCount)} total={total}/><Figure label="Needs Attention" value={num(metrics?.needsAttentionCount)} total={total}/><Figure label="At Risk" value={num(metrics?.atRiskCount)} total={total}/><Figure label="No Evidence" value={num(metrics?.noEvidenceCount)} total={total}/></div></Panel>
 <Panel title="Class Attention Summary" detail="Rules over your gradebook — no model involved."><div className="attention-summary"><strong>{missingStudents?`${missingStudents} student${missingStudents===1?" has":"s have"} past-due work.`:average!==null&&average<70?`The class average is ${pct(average)}.`:graded===0?"No graded work yet in this class.":"No widespread problem detected."}</strong><p>{missingStudents?"Send reminders and plan a short catch-up window.":"Keep monitoring progress and use targeted practice where needed."}</p></div></Panel>
 {groups.length>0&&<Panel title="Learning Groups" detail="Suggestions from the same gradebook figures shown above."><div className="stacked-list">{groups.map((g,i)=><article className="group-row" key={str(g.id)??i}><strong>{str(g.name)??"Learning group"}</strong><span>{str(g.purpose)}</span><small>{list(g.members).map(m=>str(m.name)).filter(Boolean).join(" · ")||"No students in this group right now."}</small></article>)}</div></Panel>}
 <Panel title="Students" detail={total?`${total} enrolled · completion counts work that has come due`:undefined}>{students.length?<div className="stacked-list">{students.map((s,i)=>{const due=num(s.graded_assignments)+num(s.awaiting_grade_assignments)+num(s.missing_assignments),handed=num(s.graded_assignments)+num(s.awaiting_grade_assignments),completion=due?Math.round(handed/due*100):null,id=str(s.id);return <button className="student-progress-row" key={id??i} onClick={()=>classId&&id&&onOpenStudent?.(classId,id)}><span><strong>{str(s.name)??"Student"}</strong><small>{pct(maybeNum(s.avg_grade))} · {num(s.graded_assignments)}/{num(s.total_assignments)} graded{num(s.missing_assignments)?` · ${num(s.missing_assignments)} missing`:""}</small></span><span className="row-status">{status(str(obj(data.statusByStudent)?.[id??""]))}</span><span className="row-completion">{pct(completion)} complete ›</span></button>})}</div>:<Empty>No students enrolled in this class yet.</Empty>}</Panel>
 <Panel title="Assignment Performance" detail={assignments.length?"Missing counts only work whose due date has passed.":undefined}>{assignments.length?<div className="stacked-list">{assignments.map((a,i)=><article className="assignment-progress-row" key={str(a.assignmentId)??i}><div><strong>{str(a.title)??"Assignment"}</strong><small>{str(a.dueDate)?`Due ${date(str(a.dueDate) as string)}`:"No due date"}</small></div><div className="assignment-progress-stats"><span>{pct(maybeNum(a.averagePercentage))}<small>Average</small></span><span>{num(a.gradedCount)}/{num(a.expectedCount)}<small>Graded</small></span><span>{num(a.missingCount)}<small>Missing</small></span></div></article>)}</div>:<Empty>No published assignments in this class yet.</Empty>}</Panel></>
}

function StudentProgress({data}:{data:Record<string,unknown>}){
 const student=obj(data.student),course=obj(data.class),progress=obj(data.progress),rollup=obj(data.rollup),questions=obj(rollup?.questions),work=list(rollup?.items),method=list(data.methodMatch),graded=num(progress?.graded_assignments),missing=num(progress?.missing_assignments),due=graded+num(progress?.awaiting_grade_assignments)+missing,handed=graded+num(progress?.awaiting_grade_assignments),completion=due?Math.round(handed/due*100):null,points=list(rollup?.gradedInDateOrder),insight=obj(data.insight);
 return <><header className="page-header student-header"><p className="section-kicker">{str(course?.name)??"Class progress"}</p><div className="student-title"><h1>{str(student?.name)??"Student progress"}</h1><span className="row-status">{status(str(data.status))}</span></div></header>
 {Boolean(data.historyIsPartial)&&<p className="progress-notice">This page reads the most recent work in detail. Older assignments are not included in the figures below.</p>}
 <section aria-label="Student summary" className="progress-overview student-overview"><Metric label="Average Grade" value={pct(maybeNum(progress?.avg_assignment_grade))} support={graded?`${graded} graded assignments`:"No graded work yet"}/><Metric label="Completion" value={pct(completion)} support={completion===null?"Nothing due yet":`${handed}/${due} of work that has come due`}/><Metric label="Missing Work" value={missing} support={missing?`${num(progress?.not_yet_due_assignments)} more not due yet`:"Nothing past due"}/>{method[0]&&<Metric label="Latest Method Match" value={pct(maybeNum(method[0].matchPercentage))} support={str(method[0].conceptName)??"Method Match evaluation"}/>}</section>
 <Panel title="Performance Over Time" detail="Effective percentage per graded assignment.">{points.length?<div className="performance-points">{points.map((p,i)=><div key={str(p.assignmentId)??i}><span>{str(p.title)??"Assignment"}</span><strong>{pct(maybeNum(p.percentage))}</strong></div>)}</div>:<Empty>No graded work yet.</Empty>}</Panel>
 {insight&&<Panel title="Student Insights"><div className="attention-summary"><p>{str(insight.overallSummary)??str(insight.overall_summary)??"Current insight is available in TeacherLyft."}</p></div></Panel>}
 <Panel title="Question-Level Results" detail={num(questions?.total)?`${num(questions?.total)} questions across ${graded} graded assignments`:undefined}>{num(questions?.total)?<div className="question-results"><Figure label="Correct" value={num(questions?.correct)} total={num(questions?.total)}/><Figure label="Incorrect" value={num(questions?.incorrect)} total={num(questions?.total)}/><Figure label="Unreadable" value={num(questions?.uncertain)} total={num(questions?.total)}/></div>:<Empty>No graded questions yet.</Empty>}</Panel>
 <Panel title="Assignment History" detail={work.length?`${work.length} published assignments`:undefined}>{work.length?<div className="stacked-list">{work.map((item,i)=><article className="history-row" key={str(item.assignmentId)??i}><div><strong>{str(item.title)??"Assignment"}</strong><small>{str(item.dueDate)?`Due ${date(str(item.dueDate) as string)}`:"No due date"}</small></div><div><strong>{pct(maybeNum(item.percentage))}</strong><span className="row-status">{state(str(item.state))}</span></div></article>)}</div>:<Empty>No published assignments in this class yet.</Empty>}</Panel>
 {method.length>0&&<Panel title="Method Match History"><div className="stacked-list">{method.map((m,i)=><article className="history-row" key={str(m.paperSubmissionId)??i}><div><strong>{str(m.assignmentTitle)??str(m.conceptName)??"Method Match"}</strong><small>{str(m.conceptName)}</small></div><strong>{pct(maybeNum(m.matchPercentage))}</strong></article>)}</div></Panel>}</>
}

function GenericDetail({kind,data}:{kind:DetailKind;data:Record<string,unknown>}){const primary=obj(data[kind])||obj(data[kind==="library"?"concept":kind==="curriculum"?"textbook":kind]),title=str(primary?.name)||str(primary?.title)||`${label(kind)} detail`;return <><header className="page-header"><p className="section-kicker">{label(kind)}</p><h1>{title}</h1>{str(primary?.className)&&<p>{str(primary?.className)}</p>}</header><ObjectSection title="Overview" value={primary}/>{Object.entries(data).filter(([k,v])=>k!==kind&&k!=="concept"&&k!=="textbook"&&v!=null).map(([k,v])=><ValueSection key={k} name={k} value={v}/>)}</>}
function ValueSection({name,value}:{name:string;value:unknown}){if(Array.isArray(value))return <section className="detail-section"><h2>{label(name)}</h2>{value.length?<div className="detail-list">{value.map((x,i)=><div className="detail-row" key={i}><Fields value={obj(x)}/></div>)}</div>:<p className="inline-empty">No {label(name).toLowerCase()} yet.</p>}</section>;return <ObjectSection title={label(name)} value={obj(value)}/>}
function ObjectSection({title,value}:{title:string;value:Record<string,unknown>|null}){return value?<section className="detail-section"><h2>{title}</h2><dl className="detail-grid"><Fields value={value}/></dl>{Object.entries(value).filter(([,v])=>Array.isArray(v)).map(([k,v])=><ValueSection key={k} name={k} value={v}/>)}</section>:null}
function Fields({value}:{value:Record<string,unknown>|null}){return value?<>{Object.entries(value).filter(([k,v])=>k!=="id"&&primitive(v)).map(([k,v])=><div className="detail-field" key={k}><dt>{label(k)}</dt><dd>{display(v)}</dd></div>)}</>:null}
function Panel({title,detail,children}:{title:string;detail?:string;children:React.ReactNode}){return <section className="progress-panel"><Heading title={title} detail={detail}/>{children}</section>}
function Metric({label,value,support}:{label:string;value:string|number;support?:string}){return <article className="metric progress-metric"><span>{label}</span><strong>{value}</strong>{support&&<small>{support}</small>}</article>}
function Heading({title,detail}:{title:string;detail?:string}){return <div className="section-heading"><h2>{title}</h2>{detail&&<span>{detail}</span>}</div>}
function Figure({label,value,total}:{label:string;value:number;total:number}){return <div className="status-figure"><strong>{value}</strong><small>{total?`${Math.round(value/total*100)}%`:"—"}</small><span className="row-status">{label}</span></div>}
function Empty({children}:{children:React.ReactNode}){return <p className="progress-empty">{children}</p>}
function obj(v:unknown):Record<string,unknown>|null{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:null} function list(v:unknown){return Array.isArray(v)?v.map(obj).filter((x):x is Record<string,unknown>=>x!==null):[]} function str(v:unknown){return typeof v==="string"&&v?v:null} function num(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v:0} function maybeNum(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v:null}
function pct(v:number|null){return v===null?"—":`${Math.round(v)}%`} function date(v:string){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v),d=match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3])):new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})} function primitive(v:unknown){return ["string","number","boolean"].includes(typeof v)||v===null} function display(v:unknown){if(v===null||v==="")return "—";if(typeof v==="boolean")return v?"Yes":"No";return String(v)} function label(v:string){return v.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/_/g," ").replace(/^./,c=>c.toUpperCase())}
function status(v:string|null){return v==="on_track"?"On Track":v==="needs_attention"?"Needs Attention":v==="at_risk"?"At Risk":"No Evidence"} function state(v:string|null){return v==="graded"?"Graded":v==="needs_revision"?"Returned for revision":v==="awaiting_grade"?"Awaiting grading":v==="missing"?"Missing":"Not due yet"}
